import Testing
import CatanEngine
@testable import CatanAI

/// Pins the exact move sequence a seeded self-play game produces.
///
/// ## What this is really guarding
/// Not the moves themselves - it is that the game is reproducible **across
/// processes**, which is the property every measurement of the bots depends
/// on. Without it you cannot replay a recorded game, cannot A/B a heuristic
/// change, and cannot bisect a failing simulation.
///
/// The obvious way to check reproducibility - play the same seed twice and
/// compare - is not enough, and believing it was is how this stayed broken.
/// Swift seeds `Set` and `Dictionary` iteration order **once per process**, so
/// two runs inside one test process agree with each other while disagreeing
/// with tomorrow's run. Four separate places let that ordering reach a
/// decision:
///
///   - `RobberHeuristics.verticesTouching` filtered a `Set` and then *summed a
///     Double* over the result. Floating-point addition is not associative, so
///     the same corners added in a different order differed in the last bit -
///     enough to flip `max(by:)` between two tiles meant to tie.
///   - `BuildPlanner.expansionTarget` picked its best vertex by strict `>`
///     while walking a `Set`, and `PlacementHeuristics.score` takes only a few
///     discrete values, so ties were the common case rather than a rare one.
///     That choice reaches every road score and then the tie pool that
///     consumes the RNG, so one flipped tie desynchronises the rest of the game.
///   - `DevCardHeuristics` flat-mapped a dictionary for Year of Plenty's two
///     cards and picked its Monopoly target with `max(by:)` over a `Set`.
///   - `SetupPhase.unroadedSettlement` took `.first` of a `Set`.
///
/// Because the hash seed is fresh in every test process, a regression in any
/// of them shows up here as a failing (not merely flaky) test most of the time.
///
/// ## If this test fails
/// Either the bots genuinely changed - in which case re-record the constants
/// below in the same commit that changed them, and say so in the message - or
/// ordering has leaked back in. To tell which: run the same seed in several
/// separate processes. If they disagree with *each other*, it is ordering.
/// Re-recorded 2026-08-30 because the bots genuinely changed: trade proposals
/// widened from strictly one-card-for-one-card to quantities up to two per
/// side, and the heuristic now composes lopsided offers. Over fifteen games
/// the proposal mix went from 1,110 one-for-ones and nothing else to 761
/// one-for-ones, 342 two-for-ones and a handful of two-for-twos. The anchor
/// measurement was re-run alongside: still 40/40 against random play, so the
/// change did not break the bot.
///
/// Re-recorded 2026-09-02 because bot-to-bot trade responses moved into
/// `GameSession`. Before that, a bot could propose a trade but the loop asked
/// the proposer—not another seat—for the next action, so every offer expired
/// unanswered at end turn. The new traces include the accept/reject moves
/// players now experience. Each value below agreed across three separate
/// release-process runs before it was pinned. A 160-game, fully seat-rotated
/// comparison against the frozen pre-change greedy anchor remained decisive
/// in every game: balanced 84.4% [78.8, 90.0], aggressive 85.0% [79.4, 90.6],
/// cautious 81.2% [75.0, 87.5]. These are 95% seed-cluster bootstrap intervals
/// generated by `scripts/analyze-bot-evaluation.py`; their overlap is
/// deliberately not presented as a ranking.
///
/// Re-recorded 2026-09-02 for the first measured personality separation:
/// Aggressive proactively uses an owned knight, and Cautious asks another
/// player before paying the bank. All five values agreed across three fresh
/// Release processes. The held-out, chair-rotated run remained fully decisive
/// and the Greedy-anchor intervals still overlap (Balanced 83.1% [77.5, 88.1],
/// Aggressive 81.9% [75.0, 88.1], Cautious 81.2% [75.6, 86.9]).
///
/// Re-recorded 2026-09-03 (seed 1234 only - the other four were unaffected)
/// because `BuildPlanner.expansionTarget` now carries a continuity bonus for
/// candidates reachable via a branch the bot has already built roads
/// toward (`expansionContinuityScale`), fixing bot road networks that read
/// as an aimless web - a real 12-point game measured 3 branch junctions and
/// 8-9 dead-end tips across only 13 roads per bot, because the target was
/// recomputed from scratch every turn with no preference for continuing the
/// direction already invested in. The new value agreed across three
/// separate debug-process runs before being pinned here.
///
/// Re-recorded 2026-09-03 (all five values) because a declined trade
/// proposal is no longer the end of the bot's trading for the turn: it now
/// retries with a different offer, up to `RulesEngine.maxTradeProposalsPerTurn`
/// (3) attempts per turn, and may escalate to a generous quantity once a
/// settlement or city target is close, replacing the old one-proposal-per-turn
/// gate that ended a bot's trading after its first offer was rejected. Every
/// game with any trade activity produces a different move sequence from
/// there on. As this file's own "If this test fails" section prescribes,
/// each new value was checked for being genuine-change rather than leaked
/// ordering by running the same seed in several separate processes: all five
/// were confirmed bit-identical across two separate-process runs, both at
/// the pre-change commit and at the new one, before being pinned here.
///
/// Re-recorded 2026-09-03 (seed 1234 only) by the final whole-branch review's
/// fix pass, which corrected two real bugs in `generousUnlockOffer`
/// (`TradeHeuristics.swift`): it could escalate to a give-quantity *worse*
/// than the ordinary offer already on the table (finding I1), and it
/// reserved one card of the give resource for no reason - the resource is by
/// construction one the target doesn't need at all (finding I4). Both are
/// genuine behavior changes to what bots propose, so a game whose trajectory
/// passes through a generous-unlock trade now legitimately diverges from the
/// pre-fix trace. Of the five pinned seeds, only 1234's trajectory touches
/// this path; the other four are unaffected and unchanged. The new value
/// (`c07d57fded64e7ae`) was confirmed identical across three separate
/// processes - two direct runs of the `sim` executable and this test's own
/// process - before being pinned here.
///
/// Re-recorded 2026-09-04 (all five values) for a road-building/dev-card
/// review of a real played game: `BuildPlanner` now credits an edge that
/// bridges two of a bot's own disconnected road pieces (`bridgesOwnFragments`,
/// both in the not-yet-holder pursuit path and the already-holder defense
/// path) - previously a bot could sit on two separate stubs indefinitely
/// because a bridge structurally could never earn the reachable/path bonuses
/// a plain extension gets, confirmed by a 90-game sim audit (53 fragmented-
/// network cases) and separately by this project's own real played game
/// (2026-09-04, bot "Ragnar") - and `DevCardHeuristics.choosePlay` now plays
/// a held Road Building card at all, which it never did before (there was no
/// branch for it), so it sat as pure dead weight every game it was drawn.
/// Every game with any road-building activity now legitimately diverges from
/// the pre-fix trace, which is all five seeds.
///
/// This re-pin also fixes a real bug that had nothing to do with bot
/// behavior: the new `bestRoadBuildingPair` (`DevCardHeuristics.swift`)
/// originally iterated `board.onBoardEdges` - a `Set`, hash-seeded per
/// process - without sorting first, so a tie between two equally-scored
/// candidate roads resolved differently run to run. `.sorted()` fixed that,
/// but seed 7 still disagreed across separate processes afterward - tracked
/// down to this file's own two `@Test` functions interfering with each other
/// under `swift-testing`'s default concurrent scheduling once these changes
/// made games long enough to make the interference reachable (confirmed by
/// isolating `seededSelfPlayReproducesExactly` alone: stable across 5
/// separate processes every time; both tests together: 3 different results
/// across 3 processes). Root cause not further isolated beyond "the two
/// tests must not run concurrently" - wrapping them in `@Suite(.serialized)`
/// (below) forces that and was confirmed to produce the identical fingerprint
/// across 3 more separate processes once applied. All five new values were
/// additionally cross-checked against direct `sim` executable runs for their
/// respective seeds before being pinned here.
private let expectedFingerprints: [UInt64: String] = [
    1: "7964368a77394abc",
    42: "77f1cbe943477e18",
    7: "e985537b0fe9ca79",
    1234: "e0be15d59b7df4c3",
    99: "deddbc538f909be8",
]

/// Whoever may act, or `nil` at game over.
private func actingPlayer(_ state: GameState) -> PlayerID? {
    switch state.phase {
    case .setupForward(let i), .setupBackward(let i),
         .rollDice(let i), .mainTurn(let i), .movingRobber(let i):
        return state.players[i].id
    case .discarding(let pending):
        return pending.sorted().first
    case .gameOver:
        return nil
    }
}

/// A move rendering whose dictionary payloads are in a fixed order - a
/// `[Resource: Int]` prints its keys in a per-process order, which would make
/// this fingerprint unstable for reasons unrelated to play.
private func canonical(_ move: GameMove) -> String {
    func table(_ amounts: [Resource: Int]) -> String {
        Resource.allCases
            .compactMap { resource in amounts[resource].map { "\(resource)=\($0)" } }
            .joined(separator: ",")
    }
    switch move {
    case .discard(let amounts):
        return "discard[\(table(amounts))]"
    case .bankTrade(let give, let get):
        return "bankTrade[\(table(give))->\(table(get))]"
    case .proposeTrade(let offer):
        return "proposeTrade[p\(offer.from.index):\(table(offer.give))->\(table(offer.want))]"
    default:
        return "\(move)"
    }
}

/// FNV-1a. Not cryptographic - it only has to change when the sequence does.
private func fingerprint(_ moves: [String]) -> String {
    var hash: UInt64 = 0xCBF2_9CE4_8422_2325
    for move in moves {
        for byte in move.utf8 {
            hash = (hash ^ UInt64(byte)) &* 0x0000_0100_0000_01B3
        }
    }
    return String(format: "%016llx", hash)
}

private func playSeededGame(seed: UInt64) -> (fingerprint: String, moves: Int, winner: PlayerID?) {
    let state = GameSetup.newGame(board: BoardGenerator.randomized(seed: seed), seed: seed)
    let seatPolicies: [any Policy] = [
        HeuristicPolicy(personality: .balanced, id: "heuristic-balanced"),
        HeuristicPolicy(personality: .aggressive, id: "heuristic-aggressive"),
        HeuristicPolicy(personality: .cautious, id: "heuristic-cautious"),
        HeuristicPolicy(personality: .balanced, id: "heuristic-balanced"),
    ]
    var seats: [PlayerID: any Policy] = [:]
    for (index, policy) in seatPolicies.enumerated() { seats[state.players[index].id] = policy }

    // Driven through `GameSession`, not by calling the bots directly.
    // This test and the `sim` harness both used to run private loops, so the
    // sequence pinned here was one no player ever actually experienced: it saw
    // the unscoped action list and had no runaway backstop, while the app had
    // both. A fingerprint of a loop nobody plays does not protect the game.
    //
    // `GameSession` seeds its own policy RNG from `policySeed`; the value below
    // is the same derivation the harness uses so the two play identical games.
    var session = GameSession(state: state, policies: seats, policySeed: seed &* 31 &+ 7)
    var trace: [String] = []

    for _ in 0..<3000 {
        guard case .seat = session.nextActor() else { break }
        guard let step = try! session.step() else { break }
        trace.append("P\(step.actor.index):\(canonical(step.move))")
    }

    var winner: PlayerID?
    if case .gameOver(let who) = session.state.phase { winner = who }
    return (fingerprint(trace), trace.count, winner)
}

/// `.serialized` is load-bearing, not stylistic. `swift-testing` runs
/// `@Test` functions concurrently by default (independent of `swift test`'s
/// own `--parallel`/`--no-parallel`, which governs its outer process-level
/// scheduling, not the library's own task scheduler) - both functions below
/// play full self-play games, and letting them run concurrently produced a
/// real, reproducible instability: seed 7's fingerprint disagreed across
/// three separate processes when both ran together, and was rock-stable
/// across five separate processes with `seededSelfPlayReproducesExactly`
/// filtered to run alone. The exact racing access was not further isolated
/// (see the 2026-09-04 changelog entry above) - `.serialized` is the
/// standard, correct fix for "these tests must not overlap" regardless of
/// the root cause, and this file's entire purpose (checking exact
/// reproducibility against hand-verified constants) is defeated by
/// concurrent noise either way.
@Suite(.serialized)
struct SelfPlayReproducibility {
    @Test func seededSelfPlayReproducesExactly() {
        for (seed, expected) in expectedFingerprints.sorted(by: { $0.key < $1.key }) {
            let result = playSeededGame(seed: seed)
            let detail = "seed \(seed): expected \(expected), got \(result.fingerprint) "
                + "(\(result.moves) moves, winner \(result.winner.map { "P\($0.index)" } ?? "none"))"
            #expect(result.fingerprint == expected, "\(detail)")
        }
    }

    @Test func replayingTheSameSeedInThisProcessAlsoMatches() {
        let seed: UInt64 = 42
        #expect(playSeededGame(seed: seed).fingerprint == playSeededGame(seed: seed).fingerprint,
                "seed \(seed) is not even self-consistent within one process")
    }
}
